name: Run Pytest on Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checks out your repository code
      - name: Set up Python
        uses: actions/setup-python@v2

        # Specify your Python version here
        with:
          python-version: "3.10.10"

      # Install all modules used in code
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run your pytest tests
      - name: Run Pytest
        run: |
          pytest
